/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.BookingManager;
import BLL.MemberManager;
import com.toedter.calendar.JDateChooser;
import java.util.Date;
import java.sql.SQLException;
import java.util.Enumeration;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractButton;
import javax.swing.JOptionPane;

/**
 *
 * @author MikeZJ
 */
public class CourtResevation extends javax.swing.JFrame
{

    private MemberManager mm;
    private BookingManager bm;

    /**
     * Creates new form CourtResevation
     */
    public CourtResevation(int id)
    {
        initComponents();
        for (int i = 0; i < 999999999; i++)
        {
            setEnabled();
        }

        try
        {
            mm = new MemberManager();
            bm = new BookingManager();
        }
        catch (Exception ex)
        {
            JOptionPane.showMessageDialog(this, "Impossible to create member", "Error 38", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        buttonGroup1 = new javax.swing.ButtonGroup();
        chkCourt1 = new javax.swing.JCheckBox();
        chkCourt2 = new javax.swing.JCheckBox();
        chkCourt3 = new javax.swing.JCheckBox();
        lblAvailable = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        rbtn0709 = new javax.swing.JRadioButton();
        rbtn0911 = new javax.swing.JRadioButton();
        rbtn1113 = new javax.swing.JRadioButton();
        rbtn1517 = new javax.swing.JRadioButton();
        rbtn1719 = new javax.swing.JRadioButton();
        rbtn1315 = new javax.swing.JRadioButton();
        rbtn2122 = new javax.swing.JRadioButton();
        rbtn1921 = new javax.swing.JRadioButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        lblDate = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        chkCourt1.setText("Court 1");

        chkCourt2.setText("Court 2");

        chkCourt3.setText("Court 3");

        lblAvailable.setText("Available courts:");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Booking"));

        buttonGroup1.add(rbtn0709);
        rbtn0709.setText("07:00-09:00");

        buttonGroup1.add(rbtn0911);
        rbtn0911.setText("09:00-11:00");

        buttonGroup1.add(rbtn1113);
        rbtn1113.setText("11:00-13:00");
        rbtn1113.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                rbtn1113ActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtn1517);
        rbtn1517.setText("15:00-17:00");

        buttonGroup1.add(rbtn1719);
        rbtn1719.setText("17:00-19:00");

        buttonGroup1.add(rbtn1315);
        rbtn1315.setText("13:00-15:00");
        rbtn1315.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                rbtn1315ActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtn2122);
        rbtn2122.setText("21:00-22:00");

        buttonGroup1.add(rbtn1921);
        rbtn1921.setText("19:00-21:00");

        lblDate.setText("Desired date:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblDate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rbtn1315)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbtn2122))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rbtn1113)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbtn1921))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rbtn0911)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbtn1719))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rbtn0709)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbtn1517)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtn0709)
                    .addComponent(rbtn1517))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtn0911)
                    .addComponent(rbtn1719))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtn1113)
                    .addComponent(rbtn1921))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtn1315)
                    .addComponent(rbtn2122))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setText("Ok");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chkCourt3)
                                    .addComponent(chkCourt2)
                                    .addComponent(chkCourt1)))
                            .addComponent(lblAvailable))
                        .addGap(0, 109, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblAvailable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkCourt1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkCourt2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkCourt3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtn1315ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_rbtn1315ActionPerformed
    {//GEN-HEADEREND:event_rbtn1315ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtn1315ActionPerformed

    private void rbtn1113ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_rbtn1113ActionPerformed
    {//GEN-HEADEREND:event_rbtn1113ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtn1113ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed

        String date = new JDateChooser().getDateFormatString();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(CourtResevation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(CourtResevation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(CourtResevation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(CourtResevation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
//                new CourtResevation().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox chkCourt1;
    private javax.swing.JCheckBox chkCourt2;
    private javax.swing.JCheckBox chkCourt3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAvailable;
    private javax.swing.JLabel lblDate;
    private javax.swing.JRadioButton rbtn0709;
    private javax.swing.JRadioButton rbtn0911;
    private javax.swing.JRadioButton rbtn1113;
    private javax.swing.JRadioButton rbtn1315;
    private javax.swing.JRadioButton rbtn1517;
    private javax.swing.JRadioButton rbtn1719;
    private javax.swing.JRadioButton rbtn1921;
    private javax.swing.JRadioButton rbtn2122;
    // End of variables declaration//GEN-END:variables

    private void setEnabled()
    {

        Date dateFromDateChooser = new JDateChooser().getDate();
        String dateString = String.format("%1$td-%1$tm-%1$tY", dateFromDateChooser);
 
        try
        {
            if (bm.getByDate(dateString).get(0).getTimeSlot() != null)
            {
                rbtn0709.setEnabled(false);
            }
            if (bm.getByDate(dateString).get(1).getTimeSlot() != null)
            {
                rbtn0911.setEnabled(false);
            }
            if (bm.getByDate(dateString).get(2).getTimeSlot() != null)
            {
                rbtn1113.setEnabled(false);
            }
            if (bm.getByDate(dateString).get(3).getTimeSlot() != null)
            {
                rbtn1315.setEnabled(false);
            }
            if (bm.getByDate(dateString).get(4).getTimeSlot() != null)
            {
                rbtn1517.setEnabled(false);
            }
            if (bm.getByDate(dateString).get(5).getTimeSlot() != null)
            {
                rbtn1719.setEnabled(false);
            }
            if (bm.getByDate(dateString).get(6).getTimeSlot() != null)
            {
                rbtn1921.setEnabled(false);
            }
            if (bm.getByDate(dateString).get(7).getTimeSlot() != null)
            {
                rbtn2122.setEnabled(false);
            }

            for (Enumeration<AbstractButton> buttons = buttonGroup1.getElements(); buttons.hasMoreElements();)
            {
                AbstractButton button = buttons.nextElement();

                if (button.isSelected())
                {
                    if (bm.getByDateAndTime(dateString, button.getText()) != null)
                    {
                        chkCourt1.setEnabled(false);
                    }
                    if (bm.getByDateAndTime(dateString, button.getText()) != null)
                    {
                        chkCourt2.setEnabled(false);
                    }
                    if (bm.getByDateAndTime(dateString, button.getText()) != null)
                    {
                        chkCourt3.setEnabled(false);
                    }
//                    button.getText();
                }
            }
        }
        catch (SQLException ex)
        {
            Logger.getLogger(CourtResevation.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
